### ISSUE TITLE
SSH wrapper script strips command line parameters

### ISSUE THREAD

**Issue by 2sheds** [butlerx/wetty#130] opened 2018-11-05 13:54 UTC
Extra options for SSH connection (port & auth) constructed by `getCommand()` are stripped by bin/ssh wrapper because it only effectively passes `$1` i.e. username and hostname.

**Comment by butlerx** [comment] 2018-11-05 14:59
Duplicate of #127

**Closed as completed** 2018-11-05 14:58 UTC
